---

- name:           Add MariaDB repository
  apt_repository: repo="deb http://mirror3.layerjet.com/mariadb/repo/{{ mariadb.version }}/ubuntu {{ ansible_distribution_release }} main"

- name:    Add keys for MariaDB repository
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db

- name: Update apt
  apt:  update_cache=yes

- name:       Install MariaDB
  apt:        pkg="{{ item }}" state=latest
  with_items:
    - "mariadb-server"
    - "python-mysqldb"

- name:       Set MariaDB root user password
  mysql_user: name="root" host="{{ item }}" password="{{ mariadb.root_password }}" login_user="root" state=present
  with_items:
    - "localhost"
  notify: Restart MariaDB

- name:     Add .my.cnf for root
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name:    Set MariaDB mysql_secure_installation
  command: mysql -ne "{{ item }}"
  with_items:
    - "DELETE FROM mysql.user WHERE User=''"
    - "DELETE FROM mysql.user WHERE User = 'root' AND Host != 'localhost'" 
    - "DROP DATABASE IF EXISTS test"
    - "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    - "FLUSH PRIVILEGES"
