---

- name: Add PostgreSQL repository GPG key
  shell: "curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /usr/share/keyrings/postgres.gpg >/dev/null"
  args:
    creates: "/usr/share/keyrings/postgres.gpg"

- name:           Add PostgreSQL repository
  apt_repository: repo="deb [arch=amd64 signed-by=/usr/share/keyrings/postgres.gpg] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" filename="postgres" update_cache=yes

- name: Install PostgreSQL
  apt:  name="postgresql-{{ postgresql_version }}" state=latest

- name: Install Psycopg2
  apt:  name="python3-psycopg2" state=latest
  when: ansible_distribution_release == 'focal' or ansible_distribution_release == 'jammy'

- name:    Save origin postgresql.conf config
  command: mv -fv "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf" "/etc/postgresql/{{ postgresql_version }}/postgresql.conf-origin" creates="/etc/postgresql/{{ postgresql_version }}/postgresql.conf-origin"

- name:     Set server.cnf config
  template: src="postgresql.conf" dest="/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
  notify:   Restart PostgreSQL
