---

- name:    Add keys for PostgreSQL repository
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name:           Add PostgreSQL repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ postgresql_distributive }}-pgdg main" update_cache=yes

- name: Install PostgreSQL
  apt:  name="{{ item }}" state=latest
  with_items:
    - "postgresql-{{ postgresql_version }}"
    - "python-psycopg2"
