---

- name:    Add keys for PostgreSQL repository
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name:           Add PostgreSQL repository
  apt_repository: repo="deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" update_cache=yes

- name: Install PostgreSQL
  apt:  name="postgresql-{{ postgresql_version }}" state=latest

- name: Install Psycopg2
  apt:  name="python3-psycopg2" state=latest
  when: ansible_distribution_release == 'focal'
