---

- name:     Check current hostname
  command:  cat /etc/hostname
  register: current_hostname

- name:    Set the hostname in /etc/hostname
  command: echo "{{ server.hostname }}" > /etc/hostname
  when:    current_hostname.stdout != server.hostname

- name:    Set the hostname
  command: hostname "{{ server.hostname }}"
  when:    current_hostname.stdout != server.hostname

- name:       Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp="^127\.0\.0\.1" line="127.0.0.1 localhost {{ server.hostname }}"
