---

- name: Update apt
  apt:  update_cache=yes
  
- name: Upgrade apt
  apt:  upgrade=dist

- name:       Install packages
  apt:        pkg="{{ item }}" state=latest
  with_items: "{{ server.packages }}"
  when:       server.packages is defined

- name:     Configure the timezone
  template: src=timezone.tpl dest=/etc/timezone
  notify:   Update tzdata
  when:     server.timezone is defined

- name: More Configure the timezone
  file: src="/usr/share/zoneinfo/{{ server.timezone }}" dest=/etc/localtime state=link force=yes backup=yes
  when: server.timezone is defined

- name:  Set default system language pack
  shell: locale-gen "{{ server.locale }}"
  when:  server.locale is defined

- name:  Set the hostname in /etc/hostname
  shell: echo "{{ server.hostname }}" > /etc/hostname
  when:  server.hostname is defined

- name:  Set the hostname
  shell: hostname "{{ server.hostname }}"
  when:  server.hostname is defined

- name:       Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp="^127\.0\.0\.1" line="127.0.0.1 localhost {{ server.hostname }}"
