---

- name:         Check current timezone
  command:      cat /etc/timezone
  register:     current_timezone
  changed_when: current_timezone.stdout != server.timezone

- name:    Configure the timezone
  command: echo "{{ server.timezone }}" > /etc/timezone
  notify:  Update tzdata
  when:    current_timezone.stdout != server.timezone

- name: More Configure the timezone
  file: src="/usr/share/zoneinfo/{{ server.timezone }}" dest=/etc/localtime state=link force=yes
  when: current_timezone.stdout != server.timezone
