---

- hosts:       web_server
  become:      yes
  become_user: root
  roles:
    - nginx
    - role:                           corpsee_site
      corpsee_site_mode:              "{{ corpsee_site_mode_test }}"
      corpsee_site_php_version:       "{{ corpsee_site_php_version_test }}"
      corpsee_site_user:              "{{ corpsee_site_user_test }}"
      corpsee_site_group:             "{{ corpsee_site_group_test }}"
      corpsee_site_localhost_user:    "{{ corpsee_site_localhost_user_test }}"
      corpsee_site_db_name:           "{{ corpsee_site_db_name_test }}"
      corpsee_site_db_user:           "{{ corpsee_site_db_user_test }}"
      corpsee_site_db_password:       "{{ corpsee_site_db_password_test }}"
      corpsee_site_db_dump_filename:  "{{ corpsee_site_db_dump_filename_test }}"
      corpsee_site_www_dir_filename:  "{{ corpsee_site_www_dir_filename_test }}"
      corpsee_site_hostname:          "{{ corpsee_site_hostname_test }}"
      corpsee_site_cron_disabled:     "{{ corpsee_site_cron_disabled_test }}"
      corpsee_site_version:           "{{ corpsee_site_version_test }}"
      corpsee_site_cert_pem_path:     "{{ corpsee_site_cert_pem_path_test }}"
      corpsee_site_cert_pem_key_path: "{{ corpsee_site_cert_pem_key_path_test }}"
