---

- name: Upgrade server packages
  apt:
    upgrade: yes
    update_cache: yes
  changed_when: no

- name: Install packages
  apt:
    name: "{{ packages_items_to_install | default([]) }}"
    state: present
