---

- name:    Add keys for repositories
  apt_key: id={{ item.key }} keyserver={{ item.keyserver }} state=present
  loop:    "{{ packages_repositories | default([]) }}"

- name:           Add repositories
  apt_repository: repo={{ item.repository }} update_cache=yes
  loop:           "{{ packages_repositories | default([]) }}"
