---

corpsee_site_mode:              debug # mode: production|debug
corpsee_site_php_version:       '8.3'
corpsee_site_user:              www-data
corpsee_site_group:             www-data
corpsee_site_localhost_user:    corpsee
corpsee_site_db_name:           corpsee_site
corpsee_site_db_user:           corpsee_site
corpsee_site_db_password:       corpsee_site
corpsee_site_db_dump_filename:  corpsee_site
corpsee_site_www_dir_filename:  public
corpsee_site_hostname:          corpsee.test
corpsee_site_dir_name:          corpsee_site
corpsee_site_cron_disabled:     yes
corpsee_site_version:           master
corpsee_site_cert_pem_path:     '~/corpsee.test.pem'
corpsee_site_cert_pem_key_path: '~/corpsee.test-key.pem'
corpsee_site_app_secret:        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
corpsee_site_ga_tracking:       'G-AAAAAAAAAA'
