---

# mode: production|debug
server_mode:     debug
server_hostname: example-hostname
server_domain:   example-hostname.test

server_timezone: UTC

server_locales:
  - en_US.UTF-8

server_default_local: en_US.UTF-8

server_openssh_port: 22


