---

- name: Create web user
  user:
    name:            "{{ webuser_user }}"
    password:        "{{ webuser_password | password_hash('sha512') }}"
    group:           "{{ webuser_group }}"
    groups:          "{{ webuser_groups }}"
    shell:           /bin/bash
    update_password: on_create

- name: Set authorized key
  authorized_key:
    user:  "{{ webuser_user }}"
    state: present
    key:   "{{lookup('file', '~/.ssh/ansible_web_server_' + webuser_user + '.pub')}}"

- name: Creates web user sudoers config
  template: src=sudoers.j2 dest="/etc/sudoers.d/{{ webuser_user }}" validate="visudo -cf %s" mode=0440

- name: Creates backup directory
  file: path="/home/{{ webuser_user }}/backup" owner="{{ webuser_user }}" group="{{ webuser_group }}" mode=0755 state=directory
