---

- name: Create web user
  user:
    name:            "{{ webuser_user }}"
    password:        "{{ webuser_password | password_hash('sha512') }}"
    group:           "{{ webuser_group }}"
    groups:          "{{ webuser_groups }}"
    shell:           /bin/bash
    update_password: on_create

- name: Set authorized key
  authorized_key:
    user:  "{{ webuser_user }}"
    state: present
    key:   "{{lookup('file', 'web_server_' + webuser_user + '.pub')}}"

- name: Create the SSH public key file for root
  copy: src="{{ role_path }}/files/web_server_github.pub" dest=/root/.ssh/web_server_github.pub mode=0600

- name: Create the SSH private key file for root
  copy: src="{{ role_path }}/files/web_server_github" dest=/root/.ssh/web_server_github mode=0600

- name: Creates web user sudoers config
  template: src=sudoers.j2 dest="/etc/sudoers.d/{{ webuser_user }}" validate="visudo -cf %s" mode=0440

- name: Creates backup directory
  file: path="/home/{{ webuser_user }}/backup" owner="{{ webuser_user }}" group="{{ webuser_group }}" mode=0755 state=directory

- name: Set env variables for crontab
  cron:
    env:   yes
    name:  "{{ item.name }}"
    value: "{{ item.value }}"
    user:  "{{ corpsee_site_user }}"
  loop:
    - { name: "USER", value: "{{ webuser_user }}" }
    - { name: "LOGNAME", value: "{{ webuser_user }}" }
    - { name: "HOME", value: "/home/{{ webuser_user }}" }
    - { name: "PATH", value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/{{ webuser_user }}/bin:/home/{{ webuser_user }}/Bin" }
    - { name: "SHELL", value: "/bin/bash" }
