---

- name: Create web user
  user:
    name:            "{{ webuser_user }}"
    password:        "{{ webuser_password | password_hash('sha512') }}"
    group:           "{{ webuser_group }}"
    groups:          "{{ webuser_groups }}"
    shell:           /bin/bash
    update_password: on_create

- name: Set authorized key
  authorized_key:
    user:  "{{ webuser_user }}"
    state: present
    key:   "{{lookup('file', '~/.ssh/ansible_web_server_' + webuser_user + '.pub')}}"
