---

- name:  Add Node.js repository
  shell: "curl -sL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | sudo -E bash -"

- name: Install Node.js
  apt:  name="nodejs" state=latest

- name: Add Yarn repository GPG key
  shell: "curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarn.gpg >/dev/null"

- name:           Add Yarn repository
  apt_repository: repo="deb [arch=amd64 signed-by=/usr/share/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" filename="yarn" update_cache=yes

- name: Install Yarn
  apt:  name="yarn" state=latest
