---

- name:  Add Node.js repository
  shell: "curl -sL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | sudo -E bash -"

- name: Install Node.js
  apt:  name="nodejs" state=latest

- name:    Add keys for Yarn repository
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present

- name:           Add Yarn repository
  apt_repository: repo="deb [arch=amd64] https://dl.yarnpkg.com/debian/ stable main" update_cache=yes

- name: Install Yarn
  apt:  name="yarn" state=latest
