---

- name:     Create Node.js setup script
  template: src=setup_nodejs_18.sh dest="/home/{{ desktop_user }}/setup_nodejs_18.sh"

- name: Set permissions for Node.js setup script
  file: path="/home/{{ corpsee_site_user }}/setup_nodejs_18.sh" owner={{ desktop_user }} group={{ desktop_user }} mode="ug=rwx,o=r"

- name:  Add Node.js repository
  shell: "sudo -E bash /home/{{ corpsee_site_user }}/setup_nodejs_18.sh"

- name: Install Node.js
  apt:  name="nodejs" state=latest

- name: Add Yarn repository GPG key
  shell: "curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarn.gpg >/dev/null"

- name:           Add Yarn repository
  apt_repository: repo="deb [arch=amd64 signed-by=/usr/share/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" filename="yarn" update_cache=yes

- name: Install Yarn
  apt:  name="yarn" state=latest
