---

### references

user-reference:        &user-reference        "corpsee"
group-reference:       &group-reference       "corpsee"
mode-reference:        &mode-reference        "debug"
timezone-reference:    &timezone-reference    "Asia/Novosibirsk"
php-version-reference: &php-version-reference "7.4"


### packages role

packages_ppa:
  - ppa:git-core/ppa
  - ppa:ansible/ansible
  - ppa:agornostal/ulauncher

packages_repositories:
  - repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    keyserver:  keyserver.ubuntu.com
    key:        0EBFCD88
  - repository: "deb [arch=amd64] http://vagrant-deb.linestarve.com/ any main"
    keyserver:  keyserver.ubuntu.com
    key:        AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
  - repository: "deb [arch=amd64] http://repo.yandex.ru/yandex-disk/deb/ stable main"
    keyserver:  keyserver.ubuntu.com
    key:        EFC4571D7C90E5AF
  - repository: "deb [arch=amd64] http://repo.yandex.ru/clickhouse/deb/stable/ main/"
    keyserver:  keyserver.ubuntu.com
    key:        E0C56BD4

packages_items_to_install:
  - acl
  - net-tools
  - aptitude
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - sendmail
  - screen
  - logrotate
  - curl
  - wget
  - jq
  - mc
  - htop
  - git
  - zsh
  - pv
  - ncdu

  - ansible
  - vagrant
  - docker-ce
  - beanstalkd
  - supervisor
  - redis-server
  - clickhouse-server
  - clickhouse-client

  - gnupg

  - keepassx
  - yandex-disk
  - virtualbox-qt
  - filezilla
  - pgadmin3
  - ulauncher
  - deepin-screenshot

  - earlyoom

packages_items_to_remove:
  - hexchat
  - transmission-gtk
  - thunderbird

packages_snap_items_to_install: []


### oh-my-zsh role

oh_my_zsh_user:  *user-reference
oh_my_zsh_group: *group-reference


### desktop role

desktop_user: *user-reference


### nginx role

nginx_mode:  *mode-reference
nginx_user:  *user-reference
nginx_group: *group-reference


### php role

php_mode:      *mode-reference
php_timezone:  *timezone-reference
php_version:   *php-version-reference
php_memory:    -1
php_fpm_user:  *user-reference
php_fpm_group: *group-reference
php_packages:
  - bcmath
  - mbstring
  - curl
  - gd
  - imagick
  - xml
  - zip
  - intl
  - sqlite3
  - xdebug
  - soap
  - imap
  - pgsql
  - mysql
  - redis


### composer role

composer_path: /usr/local/bin/composer


### postgresql role

postgresql_version:  13
postgresql_timezone: *timezone-reference


### postgresql_desktop role

postgresql_desktop_user:  *user-reference
postgresql_desktop_group: *group-reference


### mariadb role

mariadb_hostname:      corpsee-desktop
mariadb_version:       "10.5"
mariadb_root_password: root
mariadb_timezone:      *timezone-reference


### nodejs role

nodejs_version: 12
