---

- name: Install RabbitMq
  apt:
    name: rabbitmq-server
    state: present

# Web: http://<host>:15672
- name: Install RabbitMq Management Plugin
  command:
    cmd: "rabbitmq-plugins enable rabbitmq_management"
