---

- name:    Add keys for MariaDB repository (trusty)
  apt_key: id=0xF1656F24C74CD1D8 keyserver={{ mariadb_repo_keyserver }} state=present
  when:    ansible_distribution_release == 'trusty'

- name:    Add keys for MariaDB repository (xenial)
  apt_key: id=0xF1656F24C74CD1D8 keyserver={{ mariadb_repo_keyserver }} state=present
  when:    ansible_distribution_release == 'xenial'

- name:    Add keys for MariaDB repository (bionic)
  apt_key: id=0xF1656F24C74CD1D8 keyserver={{ mariadb_repo_keyserver }} state=present
  when:    ansible_distribution_release == 'bionic'

- name:    Add keys for MariaDB repository (focal)
  apt_key: id=0xF1656F24C74CD1D8 keyserver={{ mariadb_repo_keyserver }} state=present
  when:    ansible_distribution_release == 'focal64'

- name:           Add MariaDB repository
  apt_repository: repo="deb {{ mariadb_repo }}/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main" update_cache=yes

- name: Install MariaDB
  apt:  name="{{ item }}" state=latest
  loop:
    - "mariadb-server"
    - "python-mysqldb"

- name:       Set MariaDB root user password
  mysql_user: name="root" host="{{ item }}" password="{{ mariadb_root_password }}" login_user="root" state=present
  loop:
    - "127.0.0.1"
    - "::1"
    - "{{ mariadb_hostname }}"
    - "localhost"
  notify: Restart MariaDB

- name:     Add .my.cnf for root
  template: src=.my.cnf dest=/root/.my.cnf owner=root group=root mode=0600
