---

- name: Add MariaDB repository GPG key
  shell: "curl -sL https://mariadb.org/mariadb_release_signing_key.asc | gpg --dearmor | tee /usr/share/keyrings/mariadb.gpg >/dev/null"
  args:
    creates: "/usr/share/keyrings/mariadb.gpg"

- name:           Add MariaDB repository
  apt_repository: repo="deb [arch=amd64 signed-by=/usr/share/keyrings/mariadb.gpg] http://mirror.mephi.ru/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main" filename="mariadb" update_cache=yes

- name: Install MariaDB+
  apt:  name="{{ item }}" state=latest
  loop:
    - mariadb-server
    - mariadb-plugin-provider-bzip2
    - mariadb-plugin-provider-lz4
    - mariadb-plugin-provider-lzma
    - mariadb-plugin-provider-lzo
    - mariadb-plugin-provider-snappy
    - python3-mysqldb

- name:       Set MariaDB root user password
  mysql_user: name="root" host="{{ item }}" password="{{ mariadb_root_password }}" login_user="root" state=present
  loop:
    - "127.0.0.1"
    - "::1"
    - "localhost"
  notify: Restart MariaDB

- name:    Save origin server.cnf config
  command: mv -fv "/etc/mysql/mariadb.conf.d/50-server.cnf" "/etc/mysql/mariadb.conf.d/50-server.cnf-origin" creates="/etc/mysql/mariadb.conf.d/50-server.cnf-origin"

- name:     Set server.cnf config
  template: src="50-server.cnf" dest="/etc/mysql/mariadb.conf.d/50-server.cnf"
  notify:   Restart MariaDB

- name:     Add .my.cnf for root
  template: src=.my.cnf dest=/root/.my.cnf owner=root group=root mode=0600

- name:         Get timezone data
  command:      mysql -NBe "SELECT COUNT(*) FROM mysql.time_zone"
  register:     mysql_timezones_count
  changed_when: false
  check_mode:   no

- name:   Ensure timezone data is imported
  shell:  "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql"
  when:   mysql_timezones_count.stdout | int < 1
  notify: Restart MariaDB
