---

- name:    Add keys for MariaDB repository
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db

- name:           Add MariaDB repository
  apt_repository: repo="deb http://mirror.timeweb.ru/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main" update_cache=yes

- name:       Install MariaDB
  apt:        pkg="{{ item }}" state=latest
  with_items:
    - "mariadb-server"
    - "python-mysqldb"

- name:       Set MariaDB root user password
  mysql_user: name="root" host="{{ item }}" password="{{ mariadb_root_password }}" login_user="root" state=present
  with_items:
    - "127.0.0.1"
    - "::1"
    - "{{ server_hostname }}"
    - "localhost"
  notify: Restart MariaDB

- name:     Add .my.cnf for root
  template: src=.my.cnf dest=/root/.my.cnf owner=root group=root mode=0600
