---

- name:    Add keys for MariaDB repository
  apt_key: url=https://mariadb.org/mariadb_release_signing_key.asc state=present

- name:           Add MariaDB repository
  apt_repository: repo="deb [arch=amd64] http://mirror.mephi.ru/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main" update_cache=yes

- name: Install MariaDB
  apt:  name=mariadb-server state=latest

- name: Install Mysqldb
  apt:  name="python3-mysqldb" state=latest

- name:       Set MariaDB root user password
  mysql_user: name="root" host="{{ item }}" password="{{ mariadb_root_password }}" login_user="root" state=present
  loop:
    - "127.0.0.1"
    - "::1"
    - "{{ mariadb_hostname }}"
    - "localhost"
  notify: Restart MariaDB

- name:     Add .my.cnf for root
  template: src=.my.cnf dest=/root/.my.cnf owner=root group=root mode=0600
