---

- name:    PHP Censor Restart Nginx
  service: name=nginx enabled=yes state=restarted

- name:    PHP Censor Restart Worker
  systemd: name="{{ php_censor_queue_name }}.service" state=started enabled=yes
