---

- name:           Add PHP repository
  apt_repository: repo="ppa:ondrej/php" update_cache=yes

- name: Install PHP
  apt: pkg="{{ item }}" state=latest
  with_items:
    - "php{{ php.version }}-cli"
    - "php{{ php.version }}-fpm"
  notify: Restart PHP-FPM

- name:       Install PHP packages
  apt:        pkg="php{{ php.version }}-{{ item }}" state=latest
  with_items: "{{ php.packages }}"
  when:       php.packages is defined
