---

- name:           Add PHP repository
  apt_repository: repo="ppa:ondrej/php" update_cache=yes

- name: Install PHP
  apt: pkg="{{ item }}" state=latest
  with_items:
    - "php{{ php.version }}-cli"
    - "php{{ php.version }}-fpm"

- name:       Install PHP packages
  apt:        pkg="php{{ php.version }}-{{ item }}" state=latest
  with_items: "{{ php.packages }}"
  when:       php.packages is defined

- name:       Save origin PHP configs
  command:    mv -fv "/etc/php/{{ php.version }}/{{ item }}/php.ini" "/etc/php/{{ php.version }}/{{ item }}/php.origin.ini" creates="/etc/php/{{ php.version }}/{{ item }}/php.origin.ini"
  with_items:
    - "cli"
    - "fpm"

- name:    Save origin PHP-FPM config
  command: mv -fv "/etc/php/{{ php.version }}/fpm/php-fpm.conf" "/etc/php/{{ php.version }}/fpm/php-fpm.origin.conf" creates="/etc/php/{{ php.version }}/fpm/php-fpm.origin.conf"

- name:    Save origin PHP-FPM www config
  command: mv -fv "/etc/php/{{ php.version }}/fpm/pool.d/www.conf" "/etc/php/{{ php.version }}/fpm/pool.d/www.origin.conf" creates="/etc/php/{{ php.version }}/fpm/pool.d/www.origin.conf"

- name:       Copy PHP configs
  template:   src=php.ini.j2 dest="/etc/php/{{ php.version }}/{{ item }}/php.ini"
  notify:     Restart PHP-FPM
  with_items:
      - "cli"
      - "fpm"

- name:       PHP-FPM config
  template:   src=php-fpm.conf.j2 dest="/etc/php/{{ php.version }}/fpm/php-fpm.conf"

- name:       PHP-FPM www config
  template:   src=www.conf.j2 dest="/etc/php/{{ php.version }}/fpm/pool.d/www.conf"

- name: Create log directory
  file: path="/var/log/php/{{ php.version }}" state=directory mode=0644 owner=www-data group=www-data

- name: Clean /etc/php
  file: path="/etc/php/{{ item }}" state=absent
  with_items: "{{ php.clean_versions }}"

- name: Clean /etc/apache2
  file: path="/etc/apache2" state=absent

- name: Clean /var/log/php-fpm.log
  file: path="/var/log/php{{ php.version }}-fpm.log" state=absent
