---

# mode: production|debug
server_mode:     production
server_hostname: corpsee
server_domain:   corpsee.com

server_packages:
  - aptitude
  - curl
  - wget
  - python-software-properties
  - mc
  - htop
  - git

server_timezone: Asia/Novosibirsk

server_locales:
  - en_US.UTF-8
  - ru_RU.UTF-8

webuser_name:   corpsee
webuser_group:  www-data
webuser_groups: sudo

# memory limit in MB
php_memory: 256

php_packages:
  - xml
  - zip
  - intl
  - bcmath
  - mbstring
  - curl
  - gd
  - imagick
  - mysql
  - pgsql
