---

### server role

server_mode:         production
server_distributive: &distributive-reference "xenial"
server_hostname:     corpsee
server_domain:       corpsee.com

server_packages:
  - aptitude
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - software-properties-common
  - python-software-properties
  - sendmail
  - mc
  - htop
  - git
  - zsh

server_timezone: Asia/Novosibirsk

server_locales:
  - en_US.UTF-8
  - ru_RU.UTF-8
  
server_default_local: en_US.UTF-8


### webuser role

webuser_name:   &user-reference "web"
#webuser_password: in secret.yml
webuser_group:  &group-reference "www-data"
webuser_groups: sudo


### nginx role

nginx_distributive: *distributive-reference
nginx_user:         *user-reference
nginx_group:        *group-reference


### php role

php_version:   7.2              # version: 5.6 | 7.0 | 7.1 | 7.2
php_memory:    256M             # memory limit in MB
php_fpm_user:  *user-reference
php_fpm_group: *group-reference

php_packages:
  - bcmath
  - mbstring
  - curl
  - gd
  - imagick
  - xml
  - zip
  - intl
  - sqlite3
  - xdebug
  - pgsql


### composer role

composer_path: /usr/local/bin/composer


### postgresql role

postgresql_distributive: *distributive-reference
postgresql_version:      10
