---

### server role

server_mode:     production
server_hostname: corpsee
server_domain:   corpsee.com

server_timezone: Asia/Novosibirsk

server_locales:
  - en_US.UTF-8
  - ru_RU.UTF-8
  
server_default_local: en_US.UTF-8

server_openssh_port: 2342


### packages role

packages_items:
  - aptitude
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - sendmail
  - logrotate
  - curl
  - wget
  - jq
  - mc
  - htop
  - git
  - zsh
  - pv


### webuser role

webuser_user:   &user-reference "web"
#webuser_password: in secret.yml
webuser_group:  &group-reference "www-data"
webuser_groups: sudo


### oh-my-zsh role

oh_my_zsh_user:  *user-reference
oh_my_zsh_group: *group-reference


### nginx role

nginx_user:  *user-reference
nginx_group: *group-reference


### php role

php_version:   7.1              # version: 5.6 | 7.0 | 7.1 | 7.2 | 7.3
php_memory:    256M             # memory limit in MB
php_fpm_user:  *user-reference
php_fpm_group: *group-reference

php_packages:
  - bcmath
  - mbstring
  - curl
  - gd
  - imagick
  - xml
  - zip
  - intl
  - sqlite3
  - xdebug
  - pgsql


### composer role

composer_path: /usr/local/bin/composer


### postgresql role

postgresql_version: 11


### php_censor role

php_censor_php_version:      7.1
php_censor_user:             *user-reference
php_censor_group:            *group-reference
php_censor_db_name:          php_censor
php_censor_db_user:          php_censor
#php_censor_db_password: in secret.yml
php_censor_db_dump_filename: php_censor
php_censor_queue_name:       php_censor
php_censor_hostname:         ci.php-censor.info
php_censor_url:              "http://ci.php-censor.info"
php_censor_from_email:       'PHP Censor CI <ci@php-censor.info>'
#php_censor_github_token: in secret.yml
php_censor_version:          1.0.2

php_censor_db_name_test:          php_censor_test
php_censor_db_user_test:          php_censor_test
#php_censor_db_password_test: in secret.yml
php_censor_db_dump_filename_test: php_censor_test
php_censor_queue_name_test:       php_censor_test
php_censor_hostname_test:         ci-test.php-censor.info
php_censor_url_test:              "http://ci-test.php-censor.info"
php_censor_from_email_test:       'PHP Censor CI Test <ci-test@php-censor.info>'
php_censor_version_test:          1.0.2


### corpsee_site role

corpsee_site_php_version:      7.1
corpsee_site_user:             *user-reference
corpsee_site_group:            *group-reference
corpsee_site_db_name:          corpsee_site
corpsee_site_db_user:          corpsee_site
#corpsee_site_db_password: in secret.yml
corpsee_site_db_dump_filename: corpsee_site
corpsee_site_hostname:         corpsee.com
corpsee_site_cron_disabled:    yes
corpsee_site_version:          master

corpsee_site_db_name_test:          corpsee_site_test
corpsee_site_db_user_test:          corpsee_site_test
#corpsee_site_db_password_test: in secret.yml
corpsee_site_db_dump_filename_test: corpsee_site_test
corpsee_site_hostname_test:         test.corpsee.com
corpsee_site_cron_disabled_test:    yes
corpsee_site_version_test:          master
