---

### server role

server_mode:         production # mode: production|debug
server_distributive: xenial
server_hostname:     corpsee
server_domain:       corpsee.com

server_packages:
  - aptitude
  - curl
  - wget
  - python-software-properties
  - mc
  - htop
  - git
  - zsh

server_timezone: Asia/Novosibirsk

server_locales:
  - en_US.UTF-8
  - ru_RU.UTF-8
  
server_default_local: en_US.UTF-8


### webuser role

webuser_name:   corpsee
#webuser_password: in secret.yml
webuser_group:  www-data
webuser_groups: sudo


### php role

php_version: 7.1  # version: 5.6 | 7.0 | 7.1
php_memory:  256M # memory limit in MB

php_packages:
  - xml
  - zip
  - intl
  - bcmath
  - mbstring
  - curl
  - gd
  - imagick
  - pgsql


### composer role

composer_path: /usr/local/bin/composer


### postgresql role

postgresql_version: 9.6
