---

#- name:    Generate SSL certificates
#  command: "certbot certonly --nginx -m {{ server_cert_email }} -d {{ item }} -d www.{{ item }}"
#  loop:    "{{ server_cert_domains | default([]) }}"

- name:      Copy Letsencrypt files to host
  unarchive: src="{{ role_path }}/files/letsencrypt.tar.gz" dest="/etc"
