---

- name:       Generate locales
  locale_gen: name="{{ item }}" state=present
  with_items: "{{ server_locales }}"
  when:       server_locales is defined

- name:     Set default locale
  template: src=locale dest=/etc/default/locale
