---

- name:         Upgrade server packages
  apt:          upgrade=yes update_cache=yes cache_valid_time=3600
  changed_when: false

- name: Install packages
  apt:  name="{{ item }}" state=latest
  loop: "{{ server_packages }}"
  when: server_packages is defined
