---

- name: Set Corpsee Site Symfony pullrequest cronjob
  cron:
    name:     "{{ corpsee_site_symfony_dir_name }} pullrequests:get (Daily)"
    user:     "{{ corpsee_site_symfony_user }}"
    minute:   "0"
    hour:     "20"
    job:      "/var/www/{{ corpsee_site_symfony_dir_name }}/current/bin/console app:update-pull-requests >> /var/www/{{ corpsee_site_symfony_dir_name }}/current/var/log/update_pull_requests.log 2>&1"
    disabled: "{{ corpsee_site_symfony_cron_disabled }}"
