---

- name:       Added auth info to .pgpass config
  lineinfile: path="/home/{{ corpsee_site_symfony_user }}/.pgpass" owner="{{ corpsee_site_symfony_user }}" group="{{ corpsee_site_symfony_group }}" mode=0600 create=yes line="127.0.0.1:5432:{{ corpsee_site_symfony_db_name }}:{{ corpsee_site_symfony_db_user }}:{{ corpsee_site_symfony_db_password }}" insertbefore=BOF

- name:          Create Corpsee Site Symfony DB
  postgresql_db: name="{{ corpsee_site_symfony_db_name }}" state=present
  become:        true
  become_user:   postgres
  register:      corpsee_site_symfony_database

- name:            Create Corpsee Site Symfony DB user
  postgresql_user: db="{{ corpsee_site_symfony_db_name }}" name="{{ corpsee_site_symfony_db_user }}" password="{{ corpsee_site_symfony_db_password }}" role_attr_flags="NOSUPERUSER,NOCREATEDB,NOCREATEROLE,NOREPLICATION" encrypted=yes priv=ALL
  become:          true
  become_user:     postgres

- name: Copy Corpsee Site Symfony DB dump to host
  copy: src="{{ role_path }}/files/{{ corpsee_site_symfony_db_dump_filename }}.sql.xz" dest="/tmp"

- name:          Restore Corpsee Site Symfony DB dump
  postgresql_db: name="{{ corpsee_site_symfony_db_name }}" state=restore target="/tmp/{{ corpsee_site_symfony_db_dump_filename }}.sql.xz" login_user="{{ corpsee_site_symfony_db_user }}" login_password="{{ corpsee_site_symfony_db_password }}" login_host="127.0.0.1"
  when:          corpsee_site_symfony_database.changed

- name:     Create Corpsee Site Symfony DB dump script
  template: src=backup_db.sh dest="/home/{{ corpsee_site_symfony_user }}/backup_db_{{ corpsee_site_symfony_db_name }}.sh"

- name:     Create Corpsee Site Symfony DB daily dump script
  template: src=backup_db_daily.sh dest="/home/{{ corpsee_site_symfony_user }}/backup_db_{{ corpsee_site_symfony_db_name }}_daily.sh"

- name: Set permissions for Corpsee Site Symfony DB dump script
  file: path="/home/{{ corpsee_site_symfony_user }}/backup_db_{{ corpsee_site_symfony_db_name }}.sh" owner={{ corpsee_site_symfony_user }} group={{ corpsee_site_symfony_group }} mode="ug=rwx,o=r"

- name: Set permissions for Corpsee Site Symfony DB daily dump script
  file: path="/home/{{ corpsee_site_symfony_user }}/backup_db_{{ corpsee_site_symfony_db_name }}_daily.sh" owner={{ corpsee_site_symfony_user }} group={{ corpsee_site_symfony_group }} mode="ug=rwx,o=r"

- name: Set Corpsee Site Symfony DB dump cronjob
  cron: minute=0 hour=21 weekday=5 name="{{ corpsee_site_symfony_hostname }} DB dump" user="{{ corpsee_site_symfony_user }}" job="~/backup_db_{{ corpsee_site_symfony_db_name }}.sh"
