---

- name:     Check if Corpsee Site directory is exists
  stat:     path="/var/www/{{ corpsee_site_dir_name }}/current"
  register: corpsee_site_directory

- name: EXIT BECAUSE ALREADY INIT
  meta: end_play
  when: corpsee_site_directory.stat.exists

- name:     Register release datetime
  command:  date +%Y-%m-%d_%H-%M-%S
  register: release_datetime

- name:        Clone latest Corpsee Site repository (LOCAL)
  git:         repo="git@github.com:corpsee/corpsee-com.git" version="{{ corpsee_site_version }}" dest="{{ role_path }}/files/{{ release_datetime.stdout }}" accept_hostkey=yes
  become:      yes
  become_user: "{{ corpsee_site_localhost_user }}"
  delegate_to: "127.0.0.1"

- name: Delete shared directories (LOCAL)
  file: path="{{ role_path }}/files/{{ release_datetime.stdout }}/{{ item }}" state=absent
  loop:
    - "www/files/pictures/x"
    - "www/files/pictures/xgray"
    - "www/files/pictures/xmin"
    - "www/files/posts"
    - "www/files/projects"
    - "www/slides"
    - "www/yanka"
  become:      yes
  become_user: "{{ corpsee_site_localhost_user }}"
  delegate_to: "127.0.0.1"

- name:    Install Corpsee Site dependencies (LOCAL)
  command: "php{{ corpsee_site_php_version }} /usr/local/bin/composer install --no-dev --optimize-autoloader --prefer-dist"
  args:
    chdir:   "{{ role_path }}/files/{{ release_datetime.stdout }}"
    creates: "{{ role_path }}/files/{{ release_datetime.stdout }}/vendor"
  become:      yes
  become_user: "{{ corpsee_site_localhost_user }}"
  delegate_to: "127.0.0.1"

- name: Delete non-production files (LOCAL)
  file: path="{{ role_path }}/files/{{ release_datetime.stdout }}/{{ item }}" state=absent
  loop:
    - ".git"
    - ".gitignore"
    - ".php-censor.yml"
    - ".travis.yml"
    - "deploy.sh"
    - "phpunit.xml"
    - "src/configs/config.production.php"
    - "src/configs/config.debug.php"
    - "www/index.production.php"
    - "www/index.debug.php"
    - "console.example"
    - "www/.htaccess"
    - "deploy"
    - "tests"
    - "cache/.gitkeep"
    - "www/files/compiled/.gitkeep"
  become:      yes
  become_user: "{{ corpsee_site_localhost_user }}"
  delegate_to: "127.0.0.1"

- name:        Archive Corpsee Site release (LOCAL)
  shell:       "tar --create --gzip --file=\"{{ role_path }}/files/{{ release_datetime.stdout }}.tar.gz\" ."
  become:      yes
  become_user: "{{ corpsee_site_localhost_user }}"
  args:
    chdir: "{{ role_path }}/files/{{ release_datetime.stdout }}"
  delegate_to: "127.0.0.1"

- name: Creates Corpsee Site release directory
  file: path="/var/www/{{ corpsee_site_dir_name }}/releases/{{ release_datetime.stdout }}" state=directory

- name:      Copy Corpsee Site release to host
  unarchive: src="{{ role_path }}/files/{{ release_datetime.stdout }}.tar.gz" dest="/var/www/{{ corpsee_site_dir_name }}/releases/{{ release_datetime.stdout }}"

- name: Set current release link
  file: src="/var/www/{{ corpsee_site_dir_name }}/releases/{{ release_datetime.stdout }}" dest="/var/www/{{ corpsee_site_dir_name }}/current" state=link

- name: Copy Corpsee Site files to host
  copy: src="{{ role_path }}/files/{{ corpsee_site_www_dir_filename }}/" dest="/var/www/{{ corpsee_site_dir_name }}/shared/www"

- name: Creates empty shared directories directory
  file: path="/var/www/{{ corpsee_site_dir_name }}/shared/{{ item }}" state=directory
  loop:
    - "logs"
    - "src/configs"

- name:     Create Corpsee Site config
  template: src=config.php dest="/var/www/{{ corpsee_site_dir_name }}/shared/src/configs/config.php"

- name:     Create Corpsee Site index.php file
  template: src=index.php dest="/var/www/{{ corpsee_site_dir_name }}/shared/www/index.php"

- name:     Create Corpsee Site console file
  template: src=console dest="/var/www/{{ corpsee_site_dir_name }}/current/console"

- name: Set shared directories links
  file: src="{{ item.src }}" dest="{{ item.dest }}" state=link
  loop:
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/files/pictures/x", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/files/pictures/x" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/files/pictures/xgray", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/files/pictures/xgray" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/files/pictures/xmin", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/files/pictures/xmin" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/files/posts", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/files/posts" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/files/projects", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/files/projects" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/slides", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/slides" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/yanka", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/yanka" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/logs", dest: "/var/www/{{ corpsee_site_dir_name }}/current/logs" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/www/index.php", dest: "/var/www/{{ corpsee_site_dir_name }}/current/www/index.php" }
    - { src: "/var/www/{{ corpsee_site_dir_name }}/shared/src/configs/config.php", dest: "/var/www/{{ corpsee_site_dir_name }}/current/src/configs/config.php" }

- name: Set permissions for Corpsee Site directory
  file: path="/var/www/{{ corpsee_site_dir_name }}" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ug=rwX,o=rX" recurse=yes

- name: Set Corpsee Site console executable
  file: path="/var/www/{{ corpsee_site_dir_name }}/current/console" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ugo+x"

- name:        Compile assets
  command:     ./console assets:compile --package frontend
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir:   "/var/www/{{ corpsee_site_dir_name }}/current"
    creates: "/var/www/{{ corpsee_site_dir_name }}/current/www/files/compiled/frontend.min.css"

- name:        Make migrations
  command:     ./console migrations:migrate -e corpsee_site
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir: "/var/www/{{ corpsee_site_dir_name }}/current"
