---

- name:     Check if Corpsee site directory is exists
  stat:     path="/var/www/{{ corpsee_site_hostname }}/current"
  register: site_directory

- name:     Register release datetime
  command:  date +%Y-%m-%d_%H-%M-%S
  register: release_datetime
  when:     not site_directory.stat.exists

- name: Clone latest Corpsee site repository
  git:  repo="git@github.com:corpsee/corpsee-com.git" version="{{ corpsee_site_version }}" dest="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}" key_file="/root/.ssh/web_server_github" accept_hostkey=yes
  when: not site_directory.stat.exists

- name: Set current release link
  file: src="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}" dest="/var/www/{{ corpsee_site_hostname }}/current" state=link
  when: not site_directory.stat.exists

- name: Copy Corpsee site files to host
  copy: src="{{ role_path }}/files/{{ corpsee_site_www_dir_filename }}/" dest="/var/www/{{ corpsee_site_hostname }}/shared/www"
  when: not site_directory.stat.exists

- name: Delete shared directories
  file: path="{{ item }}" state=absent
  loop:
    - "/var/www/{{ corpsee_site_hostname }}/current/www/files/pictures/x"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/files/pictures/xgray"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/files/pictures/xmin"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/files/posts"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/files/projects"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/slides"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/yanka"
  when: not site_directory.stat.exists

- name: Creates logs directory
  file: path="/var/www/{{ corpsee_site_hostname }}/shared/logs" state=directory
  when: not site_directory.stat.exists

- name:     Create Corpsee site config
  template: src=config.php dest="/var/www/{{ corpsee_site_hostname }}/shared/src/configs/config.php"
  when:     not site_directory.stat.exists

- name:     Create Corpsee site index.php file
  template: src=index.php dest="/var/www/{{ corpsee_site_hostname }}/shared/www/index.php"
  when:     not site_directory.stat.exists

- name: Set shared directories links
  file: src="{{ item.src }}" dest="{{ item.dest }}" state=link
  loop:
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/pictures/x", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/files/pictures/x" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/pictures/xgray", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/files/pictures/xgray" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/pictures/xmin", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/files/pictures/xmin" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/posts", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/files/posts" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/projects", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/files/projects" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/slides", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/slides" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/yanka", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/yanka" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/logs", dest: "/var/www/{{ corpsee_site_hostname }}/current/logs" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/index.php", dest: "/var/www/{{ corpsee_site_hostname }}/current/www/index.php" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/src/configs/config.php", dest: "/var/www/{{ corpsee_site_hostname }}/current/src/configs/config.php" }
  when: not site_directory.stat.exists

- name: Delete non-production files
  file: path="{{ item }}" state=absent
  loop:
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/.git"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/.gitignore"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/.php-censor.yml"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/.travis.yml"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/deploy.sh"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/phpunit.xml"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/src/configs/config.production.php"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/src/configs/config.debug.php"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/index.production.php"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/index.debug.php"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/.htaccess"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/deploy"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/tests"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/cache/.gitkeep"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/compiled/.gitkeep"
  when: not site_directory.stat.exists

- name: Set permitions for Corpsee site directory
  file: path="/var/www/{{ corpsee_site_hostname }}" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ug=rwX,o=rX" recurse=yes
  when: not site_directory.stat.exists

- name: Set Corpsee site console executable
  file: path="/var/www/{{ corpsee_site_hostname }}/current/console" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ugo+x"
  when: not site_directory.stat.exists

- name:        Install Corpsee site dependencies
  command:     composer install --no-dev --optimize-autoloader
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir:   "/var/www/{{ corpsee_site_hostname }}/current"
    creates: "/var/www/{{ corpsee_site_hostname }}/current/vendor"
  when: not site_directory.stat.exists

- name:        Compile assets
  command:     ./console assets:compile --package frontend
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir:   "/var/www/{{ corpsee_site_hostname }}/current"
    creates: "/var/www/{{ corpsee_site_hostname }}/current/www/files/compiled/frontend.min.css"
  when: not site_directory.stat.exists

- name:        Make migrations
  command:     ./console migrations:migrate -e corpsee_site
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir: "/var/www/{{ corpsee_site_hostname }}/current"
  when: not site_directory.stat.exists
