---

- name: Set Corpsee site pullrequest cronjob
  cron:
    name:     "{{ corpsee_site_dir_name }} pullrequests:get (Daily)"
    user:     "{{ corpsee_site_user }}"
    minute:   "0"
    hour:     "20"
    job:      "/var/www/{{ corpsee_site_dir_name }}/current/console pullrequests:get >> /var/www/{{ corpsee_site_dir_name }}/current/logs/pullrequests_get.log 2>&1"
    disabled: "{{ corpsee_site_cron_disabled }}"
