---

- name: Copy Corpsee site DB dump to host
  copy: src="{{ role_path }}/files/{{ corpsee_site_db_dump_filename }}.sql" dest="/tmp"

- name:          Create Corpsee site DB
  postgresql_db: name="{{ corpsee_site_db_name }}" state=present
  become:        true
  become_user:   postgres
  register:      corpsee_site_database

- name:            Create Corpsee site DB user
  postgresql_user: db="{{ corpsee_site_db_name }}" name="{{ corpsee_site_db_user }}" password="{{ corpsee_site_db_password }}" role_attr_flags="NOSUPERUSER,NOCREATEDB" encrypted=yes priv=ALL
  become:          true
  become_user:     postgres

- name:          Restore Corpsee site DB dump
  postgresql_db: name="{{ corpsee_site_db_name }}" state=restore target="/tmp/{{ corpsee_site_db_dump_filename }}.sql" login_user="{{ corpsee_site_db_user }}" login_password="{{ corpsee_site_db_password }}" login_host=localhost
  when:          corpsee_site_database.changed

- name:     Check if Corpsee site directory is exists
  stat:     path="/var/www/{{ corpsee_site_hostname }}/current"
  register: site_directory

- name: Create the SSH public key file
  copy: content="{{lookup('file', '~/.ssh/github.pub')}}" dest=/root/.ssh/github.pub mode=0600

- name: Create the SSH private key file
  copy: content="{{lookup('file', '~/.ssh/github')}}" dest=/root/.ssh/github mode=0600

- name: Clone latest Corpsee site repository
  git:  repo="git@github.com:corpsee/corpsee-com.git" dest="/var/www/{{ corpsee_site_hostname }}/current" key_file="/root/.ssh/github" accept_hostkey=yes
  when: not site_directory.stat.exists

- name: Copy Corpsee site files to host
  copy: src="{{ role_path }}/files/www" dest="/var/www/{{ corpsee_site_hostname }}/current"

- name: Creates logs directory
  file: path="/var/www/{{ corpsee_site_hostname }}/current/logs" state=directory

- name:     Create Corpsee site config
  template: src=config.php dest="/var/www/{{ corpsee_site_hostname }}/current/src/configs/config.php"

- name:     Create Corpsee site index.php file
  template: src=index.php dest="/var/www/{{ corpsee_site_hostname }}/current/www/index.php"

- name:       Delete non-production files
  file:       path="{{ item }}" state=absent
  with_items:
    - "/var/www/{{ corpsee_site_hostname }}/current/.git"
    - "/var/www/{{ corpsee_site_hostname }}/current/src/configs/config.production.php"
    - "/var/www/{{ corpsee_site_hostname }}/current/src/configs/config.debug.php"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/index.production.php"
    - "/var/www/{{ corpsee_site_hostname }}/current/www/index.debug.php"

- name: Set permitions for Corpsee site directory
  file: path="/var/www/{{ corpsee_site_hostname }}/current" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ug=rwX,o=rX" recurse=yes

- name: Set Corpsee site console executable
  file: path="/var/www/{{ corpsee_site_hostname }}/current/console" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ugo+x"

- name:        Install Corpsee site dependencies
  command:     composer install --no-dev --optimize-autoloader
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir:   "/var/www/{{ corpsee_site_hostname }}/current"
    creates: "/var/www/{{ corpsee_site_hostname }}/current/vendor"

- name:        Compile assets
  command:     ./console assets:compile --package frontend
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir:   "/var/www/{{ corpsee_site_hostname }}/current"
    creates: "/var/www/{{ corpsee_site_hostname }}/current/www/files/compiled/frontend.min.css"

#- name:        Make migrations
#  command:     ./console migrations:migrate -e corpsee_site
#  become:      yes
#  become_user: "{{ corpsee_site_user }}"
#  when:        not site_directory.stat.exists
#  args:
#    chdir: "/var/www/{{ corpsee_site_hostname }}/current"

- name:     Create Corpsee site host
  template: src=corpsee_site.conf dest="/etc/nginx/sites-available/{{ corpsee_site_hostname }}.conf"

- name:   Enable Corpsee site host
  file:   src="/etc/nginx/sites-available/{{ corpsee_site_hostname }}.conf" dest="/etc/nginx/sites-enabled/{{ corpsee_site_hostname }}.conf" state=link
  notify: Restart Nginx
