---

- name:           Add Nginx repository
  apt_repository: repo="ppa:nginx/stable" update_cache=yes

- name: Install Nginx
  apt:  pkg=nginx state=latest

- name:    Save origin Nginx config
  command: mv -fv /etc/nginx/nginx.conf /etc/nginx/nginx.origin.conf creates=/etc/nginx/nginx.origin.conf
  
- name:     Copy Nginx config
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf
  notify:   Restart nginx
  
- name: Disable default host
  file: path="/etc/nginx/sites-enabled/default" state=absent force=yes
  
- name: Disable default host directory
  file: path="/var/www/html" state=absent force=yes
