---

- hosts:       desktop
  become:      true
  become_user: root
  roles:
    - mint
    - packages
    - oh_my_zsh
    - desktop
    - nginx
    - { role: php, php_version: "7.4" }
    - { role: php, php_version: "8.0" }
    - { role: php, php_version: "8.1" }
    - { role: php, php_version: "8.2" }
    - { role: php, php_version: "8.3" }
    - { role: php_default, php_version: "8.3" }
    - golang
    - composer
    - postgresql
    - postgresql_desktop
    - mariadb
    - rabbitmq
    - docker
    - unity3d
