---

- hosts:       web-server
  become:      true
  become_user: root
  vars_files:
    - vars/all.yml
    - vars/secret.yml
  roles:
    - server
    - nginx
    - php
    - composer
    - postgresql
    - mariadb
