all:
  children:
    web_server:
      hosts:
        111.111.111.111:
          ansible_python_interpreter: "/usr/bin/python3.8"
          ansible_port:               2222
          corpsee_site_cron_disabled: no
