---

- name:    Add keys for Docker repository
  apt_key: id="0EBFCD88" keyserver="keyserver.ubuntu.com" state=present

- name:           Add Docker repository
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" update_cache=yes

- name: Install Docker CE
  apt:  name="docker-ce" state=latest

- name: Adding user to Docker group
  user: name="{{ docker_user }}" groups="docker" append=yes
