---

- name:     Check Composer
  stat:     path="{{ composer.path }}"
  register: composer_bin

- name: Download Composer installer
  get_url:
    url:  https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists
  
- name:    Run Composer installer
  command: php -d memory_limit=-1 composer-installer.php chdir=/tmp
  when:    not composer_bin.stat.exists
  
- name:    Move Composer to global path
  command: mv /tmp/composer.phar "{{ composer.path }}" creates="{{ composer.path }}"
  when:    not composer_bin.stat.exists
  
- name:         Update Composer
  command:      php -d memory_limit=-1 "{{ composer.path }}" self-update
  register:     composer_update
  changed_when: "'Updating to version' in composer_update.stdout"

- name: Clean Composer installer
  file: path="/tmp/composer-installer.php" state=absent
