---

- hosts:       desktop
  become:      true
  become_user: root
  roles:
    - nginx
    - { role: php, php_version: 7.1 }
    - { role: php, php_version: 7.0 }
    - { role: php, php_version: 5.6 }
    - composer
    - postgresql
