---

- hosts:       web-server
  become:      yes
  become_user: root
  roles:
    - nginx
    - role:                              php_censor
      php_censor_db_name:                "{{ php_censor_db_name_test }}"
      php_censor_db_user:                "{{ php_censor_db_user_test }}"
      php_censor_db_password:            "{{ php_censor_db_password_test }}"
      php_censor_db_dump_filename:       "{{ php_censor_db_dump_filename_test }}"
      php_censor_artifacts_dir_filename: "{{ php_censor_artifacts_dir_filename_test }}"
      php_censor_queue_name:             "{{ php_censor_queue_name_test }}"
      php_censor_hostname:               "{{ php_censor_hostname_test }}"
      php_censor_url:                    "{{ php_censor_url_test }}"
      php_censor_from_email:             "{{ php_censor_from_email_test }}"
      php_censor_version:                "{{ php_censor_version_test }}"
