---

- hosts:       web_server
  become:      yes
  become_user: root
  roles:
    - role:                                  php_censor_release
      php_censor_db_name:                    "{{ php_censor_db_name_test }}"
      php_censor_db_user:                    "{{ php_censor_db_user_test }}"
      php_censor_db_password:                "{{ php_censor_db_password_test }}"
      php_censor_queue_name:                 "{{ php_censor_queue_name_test }}"
      php_censor_hostname:                   "{{ php_censor_hostname_test }}"
      php_censor_url:                        "{{ php_censor_url_test }}"
      php_censor_from_email:                 "{{ php_censor_from_email_test }}"
      php_censor_periodical_config_filename: "{{ php_censor_periodical_config_filename_test }}"
