---

- hosts:        web-server
  become:       true
  become_user:  root
  gather_facts: false
  pre_tasks:
    - name:         Install python 2.7 as python for Ansible (xenial)
      raw:          test -e /usr/bin/python || (apt -y update && apt -y install python-minimal)
      changed_when: false

    - name:         Install aptitude for Ansible (xenial)
      raw:          test -e aptitude || (apt -y update && apt -y install aptitude)
      changed_when: false

    - name:  Setup and gather facts
      setup:
  roles:
    - server
    - webuser
    - nginx
    - php
    - composer
    - postgresql
    - php_censor
