---

- name:     Register release datetime
  command:  date +%Y-%m-%d_%H-%M-%S
  register: release_datetime

- name: Clone latest Corpsee site repository
  git:  repo="git@github.com:corpsee/corpsee-com.git" version="{{ corpsee_site_version }}" dest="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}" key_file="/root/.ssh/web_server_github" accept_hostkey=yes

- name: Delete shared directories
  file: path="{{ item }}" state=absent
  loop:
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/pictures/x"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/pictures/xgray"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/pictures/xmin"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/posts"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/projects"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/slides"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/yanka"

- name: Set shared directories links
  file: src="{{ item.src }}" dest="{{ item.dest }}" state=link
  loop:
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/pictures/x", dest: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/pictures/x" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/pictures/xgray", dest: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/pictures/xgray" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/pictures/xmin", dest: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/pictures/xmin" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/posts", dest: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/posts" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/files/projects", dest: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/projects" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/slides", dest: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/slides" }
    - { src: "/var/www/{{ corpsee_site_hostname }}/shared/www/yanka", dest: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/yanka" }

- name: Set logs directory link
  file: src="/var/www/{{ corpsee_site_hostname }}/shared/logs" dest="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/logs" state=link

- name:     Create Corpsee site config
  template: src=config.php dest="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/src/configs/config.php"

- name:     Create Corpsee site index.php file
  template: src=index.php dest="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/index.php"

- name: Delete non-production files
  file: path="{{ item }}" state=absent
  loop:
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/.git"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/src/configs/config.production.php"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/src/configs/config.debug.php"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/index.production.php"
    - "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/index.debug.php"

- name: Set permitions for Corpsee site directory
  file: path="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ug=rwX,o=rX" recurse=yes

- name: Set Corpsee site console executable
  file: path="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/console" owner={{ corpsee_site_user }} group={{ corpsee_site_group }} mode="ugo+x"

- name:        Install Corpsee site dependencies
  command:     composer install --no-dev --optimize-autoloader
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir:   "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}"
    creates: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/vendor"

- name:        Compile assets
  command:     ./console assets:compile --package frontend
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir:   "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}"
    creates: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}/www/files/compiled/frontend.min.css"

- name:        Make migrations
  command:     ./console migrations:migrate -e corpsee_site
  become:      yes
  become_user: "{{ corpsee_site_user }}"
  args:
    chdir: "/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}"

- name: Set current release link
  file: src="/var/www/{{ corpsee_site_hostname }}/releases/{{ release_datetime.stdout }}" dest="/var/www/{{ corpsee_site_hostname }}/current" state=link
