---

php_mode:            debug    # mode: production|debug
php_timezone:        UTC
php_version:         "8.1"    # version: 7.4 ... 8.4
php_memory:          128M     # memory limit in MB
php_fpm_user:        www-data
php_fpm_group:       www-data
php_packages:
  - bcmath
  - mbstring
  - curl
  - gd
  - imagick
  - xml
  - zip
  - intl
  - sqlite3
  - xdebug
  - soap
  - imap
